name: Linter check - sources

on:
  pull_request:
    paths:
      - 'bpl/**'
      - '.github/workflows/bpl_linter.yml'
    types: [opened,synchronize]

jobs:
  static_check:
    name: Run Python linter on sources
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run pylint on sources
        run: |
          pylint bpl